### ISSUE TITLE
runtime compile path

### ISSUE THREAD

**Issue by paulwratt** [HamAndEggs/seabang#3]
`~/tmp/seabang/home/pi/build/0-rpi/seabang/seabang/`

is that folder path due to the library you include in seabang source?

`/home/pi/build/0-rpi/seabang/seabang/` was where I built the seabang binary

a runtime option to set the tmp path might be useful. if I am doing stuff I _dont_ need a debugger or profiller for then `/tmp` & `~/tmp` are fine.

also I am thinking of "years to come" and running a seabang enabled code file in a "whats this", so combined with the inverse of the above, `./seabang/` would be more useful (it still keeps the current folder clean).

I need to use seabang more, I dont use cmake much either, so I dont know how this might affect that

**Comment by HamAndEggs** [comment]
The tmp path was one I came up with. So I am free to change it. I set it up like this to avoid any clashes. 
Its /tmp/seabang/{THE FULL PATH TO THE SOURCE FILE}

I should be able to add a build option, environment var option and a command line just as I did with the compiler. Seems a reasonable thing to have. It's would set the base folder part. I will always need to add to that path one based on where the source file is to avoid clashing. Maybe the command line one could give full control. I'll have to have a think about the security issues with doing that. Maybe restrict it.

**Comment by HamAndEggs** [comment]
I have added a define called SEABANG_TEMPORAY_FOLDER. There is also an environment var that is also called SEABANG_TEMPORAY_FOLDER. To prevent clashes with file names these options still need to append a path to them. Also there is a command line option --seabang-temp-path. If used then no extra path is added and so you need to ensure it's not going to cause issues.

**Comment by paulwratt** [comment]
Thats a good solution, and the command line option would be use with `./.seabang` 

Cheers
